Requirement already satisfied: xgboost in /Users/mihai/Desktop/Git/GitLab/.venv/lib/python3.9/site-packages (2.1.4)
Requirement already satisfied: numpy in /Users/mihai/Desktop/Git/GitLab/.venv/lib/python3.9/site-packages (from xgboost) (2.0.2)
Requirement already satisfied: scipy in /Users/mihai/Desktop/Git/GitLab/.venv/lib/python3.9/site-packages (from xgboost) (1.13.1)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [8]:
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [9]:
df = pd.read_csv('../data/processed/german_credit_data_preprocessed_final.csv')
df

,Age,Job,Saving accounts,Checking account,Credit amount,Duration,Risk,Sex_male,Housing_own,Housing_rent,Purpose_car,Purpose_domestic appliances,Purpose_education,Purpose_furniture/equipment,Purpose_radio/TV,Purpose_repairs,Purpose_vacation/others
0,2.766456,2,1,1,-0.745131,-1.236478,1,1,1,0,0,0,0,0,1,0,0
1,-1.191404,2,1,2,0.949817,2.248194,0,0,1,0,0,0,0,0,1,0,0
2,1.183312,1,1,1,-0.416562,-0.738668,1,1,1,0,0,0,1,0,0,0,0
3,0.831502,2,1,1,1.634247,1.750384,1,1,0,0,0,0,0,1,0,0,0
4,1.535122,2,1,1,0.566664,0.256953,0,1,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,-0.399832,1,1,1,-0.544162,-0.738668,1,0,1,0,0,0,0,1,0,0,0
996,0.391740,3,1,1,0.207612,0.754763,1,1,1,0,1,0,0,0,0,0,0
997,0.215835,2,1,1,-0.874503,-0.738668,1,1,1,0,0,0,0,0,1,0,0
998,-1.103451,2,1,1,-0.505528,1.999289,0,1,0,0,0,0,0,0,1,0,0
999,-0.751642,2,2,2,0.462457,1.999289,1,1,1,0,1,0,0,0,0,0,0

In [10]:
X = df.drop('Risk', axis=1)
y= df['Risk']
X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size = 0.2,
    random_state=42,
    stratify = y

)

In [11]:
models ={
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)  
}